// Derived from http://json.org
grammar Formula2;

operation  : START* ARGUMENT WHITESPACE* ARGUMENT_SEPERATOR WHITESPACE* ARGUMENT END*;
/*
 * Lexer Rules
 */
ARGUMENT : EXPRESSION | NUMBER;
EXPRESSION : START* NUMBER WHITESPACE* ARGUMENT_SEPERATOR WHITESPACE* NUMBER END*;
START : WHITESPACE* OPERATION WHITESPACE* '(' WHITESPACE*;
END : WHITESPACE* ')';
NUMBER     : [0-9]+;
OPERATION : ('DIV') | ('MUL') | ('SUM') | ('SUB');
ARGUMENT_SEPERATOR : ',';
WHITESPACE : ' ' -> skip ;